### ISSUE TITLE
Small Ores

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/galacticgreg#1]
Please make the small ores not generate in the top most layer on the moon and mars (Moon Turf and Mars Surface Rock) because it just doesn't look very good.
<a href="http://imgur.com/a1K5AAw"><img src="http://i.imgur.com/a1K5AAw.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/Csj5Q0I"><img src="http://i.imgur.com/Csj5Q0I.jpg" title="source: imgur.com" /></a>

**Comment by Blood-Asp** [comment]
In what version of GalacticGreg is this happening? I thought to have fixed this, but seems not the case. Maybe Galacticraft did another change that broke my stone filter.

**Comment by Nex4rius** [comment]
GalacticGreg-0.5

**Comment by Blood-Asp** [comment]
Now fixed in GG0.6. Ores on mars are now with vanilla stone textures instead of red granite, but absolutely no idea what is messing that up.
