### ISSUE TITLE
Processing 

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/galacticgreg#2]
Please add processing for the moon and mars blocks :)

Something like getting Helium3 out of moon blocks and getting tiny piles of iron out of mars blocks (red color comes from rust).

**Comment by Blood-Asp** [comment]
Thought about this some time ago and again forgot about it. Now i have a reminder here. xD

**Comment by pyure** [comment]
DS, can you think up specific examples of sensible, quasi-realistic processing?

**Comment by Blood-Asp** [comment]
Uploaded GG0.6 With some new recipes.
