### ISSUE TITLE
Doubled entries in worldgen.cfg

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/galacticgreg#4]
Some entries are doubled in worldgen config and I never know which ones are correct. (GG0.6 + GT5.09)

B:ore.mix.naquadah_false=false
B:ore.mix.naquadah_true=true

Also I suppose you will be removing the code from GG about End Asteroids since GT5.09 has them natively.

**Comment by Blood-Asp** [comment]
I will make GG detect the GT version and changes it's defaults accordingly.
