### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Shazuli** [Blood-Asp/galacticgreg#9]
Hi!

I'm using Gregtech 6.03.13, IC2 2-2.2.823-experimental, GalacticraftCore-1.7-3.0.12.460, Galacticraft-Planets-1.7-3.0.12.460, MicdoodleCore-1.7-3.0.12.460, GalaxySpace-1.0.8+STABLE and your mod GalacticGreg-1.11. I've had problems with the game crashing when I load the game with your mod active. When it's not in use all the other mods seems to work just fine for me. I have tried diffrent versions of your mod but as expected it doesn't work with latest Gregtech. I have tried to individualy disable each mod except GC, GT and your mod (and IC2 ofc), but with no luck. Is there a core I'm missing or is there information I have missed for some reason? Anyways, heres the crash report:

[crash-2016-08-09_13.42.52-client.txt](https://github.com/Blood-Asp/galacticgreg/files/408834/crash-2016-08-09_13.42.52-client.txt)

**Comment by bear989** [comment]
this is from when greg changed Banded Iron to Hematite I believe, I am having the same crash
http://pastebin.com/BAKa2dNh

**Comment by Blood-Asp** [comment]
Fixed by https://github.com/Blood-Asp/galacticgreg/pull/10
